name: DL2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.6.2
  - appdirs=1.4.4
  - arrow=1.2.3
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - blessed=1.19.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cachecontrol=0.12.11
  - cachy=0.3.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cleo=0.8.1
  - click=8.1.3
  - clikit=0.6.2
  - colorama=0.4.6
  - contourpy=1.0.5
  - crashtest=0.3.1
  - croniter=1.3.14
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - dateutils=0.6.12
  - dbus=1.13.18
  - deepdiff=6.2.2
  - distlib=0.3.6
  - docker-pycreds=0.4.0
  - expat=2.4.8
  - fastapi=0.88.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - html5lib=1.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.4.1
  - importlib_metadata=6.4.1
  - inquirer=3.1.3
  - intel-openmp=2021.4.0
  - itsdangerous=2.1.2
  - jaraco.classes=3.2.3
  - jeepney=0.8.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lightning=2.0.1.post0
  - lightning-cloud=0.5.33
  - lightning-utilities=0.8.0
  - lockfile=0.12.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mdurl=0.1.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=9.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - ordered-set=4.1.0
  - packaging=20.9
  - pastel=0.2.1
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pillow=9.4.0
  - pip=23.0.1
  - pkginfo=1.9.6
  - platformdirs=3.1.1
  - ply=3.11
  - poetry=1.1.15
  - poetry-core=1.0.8
  - pooch=1.4.0
  - protobuf=3.20.3
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pydantic=1.9.1
  - pygments=2.15.0
  - pyjwt=2.6.0
  - pylev=1.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-multipart=0.0.6
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-lightning=2.0.1.post0
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readchar=4.0.5
  - readline=8.2
  - requests=2.28.1
  - requests-toolbelt=0.9.1
  - rich=13.3.4
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - secretstorage=3.3.3
  - sentry-sdk=1.20.0
  - setproctitle=1.2.2
  - setuptools=66.0.0
  - shellingham=1.5.1
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - starlette=0.22.0
  - starsessions=1.3.0
  - sympy=1.11.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomlkit=0.11.7
  - torchaudio=2.0.0
  - torchmetrics=0.11.4
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - urllib3=1.26.15
  - uvicorn=0.21.1
  - virtualenv=20.21.0
  - wandb=0.15.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - websockets=10.3
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - mpmath==1.2.1
      - pyqt5-sip==12.11.0
